development:
  user: fedoraAdmin
  password: fedoraAdminPass
  url: http://localhost:8080/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fcrepo/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fcrepo/rest
  base_path: /prod
